"""initial_schema

Revision ID: 753f503bb8a7
Revises:
Create Date: 2026-06-23 14:04:25.937906

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "753f503bb8a7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "disk_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("device", sa.String(), nullable=False),
        sa.Column("mountpoint", sa.String(), nullable=False),
        sa.Column("total_bytes", sa.Float(), nullable=False),
        sa.Column("used_bytes", sa.Float(), nullable=False),
        sa.Column("free_bytes", sa.Float(), nullable=False),
        sa.Column("usage_percent", sa.Float(), nullable=False),
        sa.Column("read_bytes_per_sec", sa.Float(), nullable=False),
        sa.Column("write_bytes_per_sec", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hardware_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cpu_usage_percent", sa.Float(), nullable=False),
        sa.Column("memory_usage_percent", sa.Float(), nullable=False),
        sa.Column("memory_total_bytes", sa.Float(), nullable=False),
        sa.Column("memory_available_bytes", sa.Float(), nullable=False),
        sa.Column("cpu_temperature_celsius", sa.Float(), nullable=True),
        sa.Column("battery_percent", sa.Float(), nullable=True),
        sa.Column("is_plugged_in", sa.Boolean(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_scores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("component_scores", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "INVESTIGATING", "RESOLVED", "DISMISSED", name="incidentstatus"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interface", sa.String(), nullable=False),
        sa.Column("bytes_sent_per_sec", sa.Float(), nullable=False),
        sa.Column("bytes_recv_per_sec", sa.Float(), nullable=False),
        sa.Column("packets_sent_per_sec", sa.Float(), nullable=False),
        sa.Column("packets_recv_per_sec", sa.Float(), nullable=False),
        sa.Column("errors_in", sa.Float(), nullable=False),
        sa.Column("errors_out", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("action_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "component",
            sa.Enum(
                "SECURITY",
                "PERFORMANCE",
                "HARDWARE",
                "NETWORK",
                "APPLICATION",
                "STORAGE",
                "DRIVER",
                "POWER",
                "STABILITY",
                "INFORMATIONAL",
                name="eventcategory",
            ),
            nullable=False,
        ),
        sa.Column("failure_probability", sa.Float(), nullable=False),
        sa.Column("predicted_time_to_failure_hours", sa.Float(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("metrics_snapshot", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", "QUARTERLY", name="reporttype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "SECURITY",
                "PERFORMANCE",
                "HARDWARE",
                "NETWORK",
                "APPLICATION",
                "STORAGE",
                "DRIVER",
                "POWER",
                "STABILITY",
                "INFORMATIONAL",
                name="eventcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("normalized_data", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("incident_id", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_insights",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("incident_id", sa.String(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum("OLLAMA", "GEMINI", "OPENAI", "ANTHROPIC", name="aiprovider"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("explanation", sa.String(), nullable=False),
        sa.Column("recommendation", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_insights")
    op.drop_table("events")
    op.drop_table("settings")
    op.drop_table("reports")
    op.drop_table("predictions")
    op.drop_table("notifications")
    op.drop_table("network_metrics")
    op.drop_table("incidents")
    op.drop_table("health_scores")
    op.drop_table("hardware_metrics")
    op.drop_table("disk_metrics")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
